<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MFMFMSF.Core\MFMFMSF.Core.csproj" />
    <ProjectReference Include="..\MFMFMSF.Infrastructure\MFMFMSF.Infrastructure.csproj" />
    <ProjectReference Include="..\MFMFMSF.Shared\MFMFMSF.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Icons\" />
    <Folder Include="Assets\Images\" />
    <Folder Include="Features\Members\Controls\" />
    <Folder Include="Features\Members\Resources\" />
    <Folder Include="Features\Members\ViewModels\" />
    <Folder Include="Features\Offering\Resources\" />
    <Folder Include="Features\Offering\ViewModels\" />
    <Folder Include="Features\Tithes\Controls\" />
    <Folder Include="Features\Tithes\Resources\" />
    <Folder Include="Features\Tithes\ViewModels\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.5" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.2" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
  </ItemGroup>

</Project>
