<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MFMFMSF.Core\MFMFMSF.Core.csproj" />
    <ProjectReference Include="..\MFMFMSF.Infrastructure\MFMFMSF.Infrastructure.csproj" />
    <ProjectReference Include="..\MFMFMSF.Shared\MFMFMSF.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\" />
    <Folder Include="Controls\" />
    <Folder Include="Assets\" />
    <Folder Include="Themes\" />
  </ItemGroup>

</Project>
